### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by montex12** [nullfx/NullFX.CRC#25]
Hello

Is possible to make NullFX.CRC Targets .NET Standard 2.0?

That will make the library compatible with all .NET implementations specified here in one shot:
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

This is useful when your library is integrated in another .NET Standard project to have a common base between .NET and .NET Framework.

Thanks

**Comment by nullfx** [comment]
will do ;)

**Comment by MatinxHT** [comment]
> will do ;)

Hi hi,

Is possible to make NullFX.CRC Targets .NET 8 too?

Thanks

**Comment by nullfx** [comment]
Ya,  I have  an update for that here remotely (did it the other day), i just haven't pushed it up yet...  been super busy lately at home / work. that update also has a fix to my build actions so they push to nuget.org / github when I PR'd stuff (i still suck at github's ci/cd stuff), which is why my last update skipped a version number 🙈

will get to it shortly (hopefully). I know 8 has been LTS for a bit now, I'll probably look into automating that (dependabot) at some point in the near future as well 😜
